function [gauss, l1, l2, l3, iL1L2L3] = GUI_hessian(im, p)

[gauss, l1, l2, l3, iL1L2L3] = jh_vs_hessianFeature( ... 
    im, p{3}, p{2}, ...
    'anisotropic', [1 1 3], ...
    'prefType', 'single');

end