global gPP

gPP.defaults = {1, 2, 12, 7, 0, 2, 2, 1000, 3};
gPP.parameterNames = { ...
    'Exclude solitary (ES)', ...
    'ES: Connectivity', ...
    'ES: Radius of NH', ...
    'ES: Threshold', ...
    'ClassificationThresh', ...
    'Connectivity', ...
    'Dimensions', ...
    'Size exclusion', ...
    'Smoothing'};
