%execution script to label + globally enumerate + consolidate labels and
%downsample for visualization

segpath = '/Users/nasimrahaman/Documents/MATLAB/MPI/Myelin/data/stin';
enumpath = [segpath '-enumlabeled']; %as generated by graphmaker
consolpath = [segpath '-consolabeled'];
downsamplepath = [consolpath, '-ds'];
docupath = '/Users/nasimrahaman/Documents/MATLAB/MPI/Myelin/graph/docs'; %not required

%---graphmaker: labeling + global enumeration + graph generator---
disp('Generating graph...')
tic;
cg = graphmaker(segpath);
toc

%---connected component on graph and save to file--- 
disp('Connected component analysis on graph...')
tic;
global cgcc;
[~, cgcc] = graphconncomp(cg);
toc

%---consolidate labels---
disp('Consolidating labels...')
tic;
cubeprocessor(enumpath, consolpath, @consolidatelabels, 'cube'); %consolidatelabels invokes the global variable cgcc
toc
% 
% %---downsample consolidated labeled directory---
% disp('Downsampling...')
% tic;
% cubeprocessor(consolpath, downsamplepath, @downsamplecube2, 'cube');
% toc
% 
% %---write to multipage tiff stack---
% %load all to supercube
% disp('Loading supercube...')
% tic;
% supercube = loadsupercube(downsamplepath);
% toc
% %write
% disp('Writing to tiff...')
% tic;
% array2tifstack(supercube, 'finaltif.tif');
% toc